services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $cloudflareService: '@service.cloudflare'

  Causal\Cloudflare\:
    resource: '../Classes/*'

  # Define generic cloudflare service
  service.cloudflare:
    class: Causal\Cloudflare\Services\CloudflareService
    factory: '@Causal\Cloudflare\Factory\CloudflareServiceFactory'

  # Add custom toolbar
  Causal\Cloudflare\Backend\Event\CloudflareClearCacheActionsEventListener:
    tags:
      - name: event.listener
        identifier: 'cloudflare/toolbar/clear-cache-actions-listener'
        event: TYPO3\CMS\Backend\Backend\Event\ModifyClearCacheActionsEvent

  # All classes that uses DI and are invoked through GeneralUtility::makeInstance are
  # required to be public
  Causal\Cloudflare\Controller\DashboardController:
    public: true

  Causal\Cloudflare\ExtensionManager\Configuration:
    public: true

  Causal\Cloudflare\Hooks\TCEmain:
    public: true

  Causal\Cloudflare\Backend\ToolbarItems\CloudflareToolbarItem:
    public: true
